Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/exec-book-template/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/usr/share/miniconda3/envs/exec-book-template/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/exec-book-template/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/exec-book-template/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/exec-book-template/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/exec-book-template/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/usr/share/miniconda3/envs/exec-book-template/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/exec-book-template/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import nibabel as nib
from nilearn.plotting import view_img

zmap = nib.load('data/unthresh_Z.nii.gz')
view_img(zmap, threshold=2.8)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/usr/share/miniconda3/envs/exec-book-template/lib/python3.7/site-packages/nibabel/pydicom_compat.py[0m in [0;36m<module>[0;34m[0m
[1;32m     32[0m [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 33[0;31m     [0;32mimport[0m [0mdicom[0m [0;32mas[0m [0mpydicom[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     34[0m [0;32mexcept[0m [0mImportError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'dicom'

During handling of the above exception, another exception occurred:

[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_6213/3597648802.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mimport[0m [0mnibabel[0m [0;32mas[0m [0mnib[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mfrom[0m [0mnilearn[0m[0;34m.[0m[0mplotting[0m [0;32mimport[0m [0mview_img[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0mzmap[0m [0;34m=[0m [0mnib[0m[0;34m.[0m[0mload[0m[0;34m([0m[0;34m'data/unthresh_Z.nii.gz'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mview_img[0m[0;34m([0m[0mzmap[0m[0;34m,[0m [0mthreshold[0m[0;34m=[0m[0;36m2.8[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/exec-book-template/lib/python3.7/site-packages/nibabel/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     41[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mspm99analyze[0m [0;32mas[0m [0mspm99[0m[0;34m[0m[0;34m[0m[0m
[1;32m     42[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mspm2analyze[0m [0;32mas[0m [0mspm2[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 43[0;31m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mnifti1[0m [0;32mas[0m [0mni1[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     44[0m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0mecat[0m[0;34m[0m[0;34m[0m[0m
[1;32m     45[0m [0;31m# object imports[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/exec-book-template/lib/python3.7/site-packages/nibabel/nifti1.py[0m in [0;36m<module>[0;34m[0m
[1;32m     26[0m [0;32mfrom[0m [0;34m.[0m[0mspm99analyze[0m [0;32mimport[0m [0mSpmAnalyzeHeader[0m[0;34m[0m[0;34m[0m[0m
[1;32m     27[0m [0;32mfrom[0m [0;34m.[0m[0mcasting[0m [0;32mimport[0m [0mhave_binary128[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 28[0;31m [0;32mfrom[0m [0;34m.[0m[0mpydicom_compat[0m [0;32mimport[0m [0mhave_dicom[0m[0;34m,[0m [0mpydicom[0m [0;32mas[0m [0mpdcm[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     29[0m [0;34m[0m[0m
[1;32m     30[0m [0;31m# nifti1 flat header definition for Analyze-like first 348 bytes[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/exec-book-template/lib/python3.7/site-packages/nibabel/pydicom_compat.py[0m in [0;36m<module>[0;34m[0m
[1;32m     34[0m [0;32mexcept[0m [0mImportError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     35[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 36[0;31m         [0;32mimport[0m [0mpydicom[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     37[0m     [0;32mexcept[0m [0mImportError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     38[0m         [0mhave_dicom[0m [0;34m=[0m [0;32mFalse[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/exec-book-template/lib/python3.7/site-packages/pydicom/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     29[0m """
[1;32m     30[0m [0;34m[0m[0m
[0;32m---> 31[0;31m [0;32mfrom[0m [0mpydicom[0m[0;34m.[0m[0mdataelem[0m [0;32mimport[0m [0mDataElement[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     32[0m [0;32mfrom[0m [0mpydicom[0m[0;34m.[0m[0mdataset[0m [0;32mimport[0m [0mDataset[0m[0;34m,[0m [0mFileDataset[0m[0;34m,[0m [0mFileMetaDataset[0m[0;34m[0m[0;34m[0m[0m
[1;32m     33[0m [0;32mimport[0m [0mpydicom[0m[0;34m.[0m[0mexamples[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/exec-book-template/lib/python3.7/site-packages/pydicom/dataelem.py[0m in [0;36m<module>[0;34m[0m
[1;32m     15[0m [0;32mfrom[0m [0mtyping[0m [0;32mimport[0m [0mAny[0m[0;34m,[0m [0mTYPE_CHECKING[0m[0;34m,[0m [0mNamedTuple[0m[0;34m[0m[0;34m[0m[0m
[1;32m     16[0m [0;34m[0m[0m
[0;32m---> 17[0;31m [0;32mfrom[0m [0mpydicom[0m [0;32mimport[0m [0mconfig[0m  [0;31m# don't import datetime_conversion directly[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     18[0m [0;32mfrom[0m [0mpydicom[0m[0;34m.[0m[0mconfig[0m [0;32mimport[0m [0mlogger[0m[0;34m[0m[0;34m[0m[0m
[1;32m     19[0m from pydicom.datadict import (

[0;32m/usr/share/miniconda3/envs/exec-book-template/lib/python3.7/site-packages/pydicom/config.py[0m in [0;36m<module>[0;34m[0m
[1;32m     98[0m """
[1;32m     99[0m [0;34m[0m[0m
[0;32m--> 100[0;31m [0mdata_element_callback_kwargs[0m[0;34m:[0m [0mdict[0m[0;34m[[0m[0mstr[0m[0;34m,[0m [0mAny[0m[0;34m][0m [0;34m=[0m [0;34m{[0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    101[0m """Set the keyword arguments passed to :func:`data_element_callback`.
[1;32m    102[0m [0;34m[0m[0m

[0;31mTypeError[0m: 'type' object is not subscriptable
TypeError: 'type' object is not subscriptable

